// product cards

export const product1 = {
    name: 'Philips Sonicare HX8911/02',
    type: 'electric toothbrush',
    feature1Key: 'Power',
    feature1Value: '1 CR5 batteries',
    feature2Key: 'Color',
    feature2Value: 'white',
    feature3Key: 'Weight',
    feature3Value: '1.1 pounds',
    feature4Key: 'Brush head',
    feature4Value: 'diamond clean',
    feature5Key: 'Travel case',
    feature5Value: 'included',
    feature6Key: 'Case charger',
    feature6Value: 'yes',
    imgSrc: './images/productImg1.jpg',
    bonusPts: 240,
    price: '95.75',
};

export const product2 = {
    name: 'Braun Series 3 ProSkin',
    type: 'electric razor',
    feature1Key: 'Power',
    feature1Value: 'rechargeble battery',
    feature2Key: 'Color',
    feature2Value: 'black',
    feature3Key: 'Weight',
    feature3Value: '11.4 ounces',
    feature4Key: 'Quickcharge',
    feature4Value: 'yes',
    feature5Key: 'Washable',
    feature5Value: 'yes',
    feature6Key: 'Head type',
    feature6Value: 'foil',
    imgSrc: './images/productImg2.jpg',
    bonusPts: 120,
    price: '110.50',
};

export const product3 = {
    name: 'Dyson Pure Hot and Cool Link',
    type: 'air purifier',
    feature1Key: 'Power',
    feature1Value: 'corded electric',
    feature2Key: 'Color',
    feature2Value: 'white',
    feature3Key: 'Volume',
    feature3Value: '1 milliliters',
    feature4Key: 'loudness',
    feature4Value: '40 dB',
    feature5Key: 'Humidifier',
    feature5Value: 'no',
    feature6Key: 'HEPA purifier',
    feature6Value: 'yes',
    imgSrc: './images/productImg3.jpg',
    bonusPts: 310,
    price: '145.90',
};

export const product4 = {
    name: 'Bodum Melior Gooseneck',
    type: 'electric kettle',
    feature1Key: 'Power',
    feature1Value: 'corded electric',
    feature2Key: 'Color',
    feature2Value: 'matte black',
    feature3Key: 'Volume',
    feature3Value: '27 ounces',
    feature4Key: 'Material',
    feature4Value: 'stainless steel',
    feature5Key: 'Surface',
    feature5Value: 'non-slip',
    feature6Key: 'Voltage',
    feature6Value: '120',
    imgSrc: './images/productImg4.jpg',
    bonusPts: 420,
    price: '67.25',
};

export const product5 = {
    name: 'Sony WF-1000XM4 Earbud',
    type: 'wireless earbuds',
    feature1Key: 'Fit type',
    feature1Value: 'in-ear',
    feature2Key: 'Battery life',
    feature2Value: '8 hrs (24 hrs with case)',
    feature3Key: 'Water resistance',
    feature3Value: 'IPX4',
    feature4Key: 'LDAC support',
    feature4Value: 'yes',
    feature5Key: 'Color',
    feature5Value: 'black, gold',
    feature6Key: 'Noise cancelling',
    feature6Value: 'yes',
    imgSrc: './images/productImg5.jpg',
    bonusPts: 150,
    price: '280',
};

export const product6 = {
    name: 'Bowflex SelectTech 552',
    type: 'adjustable dumbbell',
    feature1Key: 'Weight',
    feature1Value: '5 - 52.5 pounds',
    feature2Key: 'Weight settings',
    feature2Value: '15',
    feature3Key: 'Material',
    feature3Value: 'steel, rubber',
    feature4Key: 'Increment step',
    feature4Value: '2.5 pounds',
    feature5Key: '',
    feature5Value: '',
    feature6Key: '',
    feature6Value: '',
    imgSrc: './images/productImg6.jpg',
    bonusPts: 240,
    price: '390.00',
};